/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.praktikumtiga;

import java.security.NoSuchAlgorithmException;

public class App
{
    public static void main(String[] args) throws Exception, NoSuchAlgorithmException
    {
        PasswordStore pass1 = new PasswordStore("Akun BCA", "1122334455", "RahasiaNegara");
        
        pass1.setCategory(PasswordStore.CAT_WEBAPP);

        System.out.println("\n\tEncrypt");
        System.out.println(pass1);
        System.out.println("\n\tDecrypt");
        System.out.println("USERNAME: " + pass1.username + "\nPASSWORD: " + pass1.getPassword());
    }
}
