/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.praktikumtiga;

import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
import java.util.ArrayList;

public class App
{
    public static void main(String[] args) throws Exception
    {
        ArrayList<PasswordStore> csvData = DataPassword.loadCSVData();

        for (PasswordStore i: csvData)
        {
            if (!DataPassword.dataPass.contains(i))
            {
                DataPassword.dataPass.addAll(csvData);
            }
        }

        new MainPage("Password Vault", 70).draw();

        DataPassword.saveCSVData();
    }
}
