/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.praktikum;

import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
import java.util.ArrayList;

public class App
{
    public static void main(String[] args)
    {
        DataPassword.loadCSVData();

        new MainPage(70).draw();
    }
}
